# Generated by Django 5.2.12 on 2026-08-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_align_professional_profile_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OWNER', 'Propietario'), ('COLLABORATOR', 'Colaborador'), ('VIEWER', 'Visor')], default='VIEWER', max_length=20),
        ),
    ]
