# Generated by Django 5.2.12 on 2026-09-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='zone',
            field=models.CharField(blank=True, choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=10),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='project',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='projects', to='core.brand'),
        ),
    ]
